[package]
name = "my-time"
version = "0.1.0"
authors = ["chj <316422663@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.42"
